name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Run golangci-lint with reviewdog
        uses: reviewdog/action-golangci-lint@v2.7.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--timeout=5m"
          reporter: github-pr-check
          level: warning

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

